### ISSUE TITLE
Toast should always visible 

### ISSUE THREAD

**Issue by carloftg** [apvarun/toastify-js#29] opened 2019-07-05 14:22 UTC
Hello,
I have the problem that the toast is coming from the bottom of the top of the page and not top or bottom of the screen so if I am scrolling the page or using it on a tall page, I cannot see the toast anymore, is there a fix? Currently, the website using it is embedded within an iframe thought I am not sure if that is matter or not. Please kindly advise,

**Comment by apvarun** [comment] 2019-07-20 07:44
Can you reproduce this issue? I wasn't able to. It works fine for me here.
https://codesandbox.io/s/competent-thompson-gfwyx

**Comment by apvarun** [comment] 2020-03-01 22:42
Closing this for now as there is no feedback. Feel free to reopen if the issue persists

**Closed by apvarun** 2020-03-01 22:42 UTC

**Comment by avimar** [comment] 2021-08-20 06:15
I had this issue, and it seems to be on mobile due to zoom. 

To reproduce:

1) Open this on mobile (I did it in chrome)
2) Pinch-zoom into the text ("Text screen 1", or any other)
... then you won't see the toasts. They show up off-screen.
Video attached.

[I don't know enough about viewports and chrome's zooming to know if this is fixable.]

https://user-images.githubusercontent.com/314077/130188477-f898bc01-547c-415a-a846-15c98dc4b31b.mp4

**Comment by apvarun** [comment] 2021-08-29 09:16
Hey @avimar 

From this video, it looks like the viewport is not set for mobile in this page. You can do it by adding the following into head tag.
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

Meanwhile, pinch to zoom will not reduce the viewport width and its just an accessibility feature.

**Comment by avimar** [comment] 2021-08-29 09:45
I'm getting the same issue on mobile when I add that line

https://codesandbox.io/s/toastify-bottom-on-scroll-forked-tojjn

**Comment by apvarun** [comment] 2021-08-29 19:17
Here is what happens to me. As I scroll the page, the toast always stays in the screen. That's the expected behaviour.

In case of pinch zoom, as I mentioned earlier, it's a screen zoom and not a page zoom. So the page width would not change as we zoom.

https://user-images.githubusercontent.com/8411309/131262700-2d32f4d4-3082-4cef-84d8-c586890ac3a2.mp4

**Comment by avimar** [comment] 2021-08-29 19:23
>Meanwhile, pinch to zoom will not reduce the viewport width and its just an accessibility feature.
> it's a screen zoom and not a page zoom. So the page width would not change as we zoom.

So if the user on mobile does a pinch-to-zoom, then there's no way to guarantee the toast will always be visible?
